joyopdf_url = http://kokugo.bunka.go.jp/kokugo_nihongo/joho/kijun/naikaku/pdf/joyokanjihyo_20101130.pdf
pdfbox_url = http://www-us.apache.org/dist/pdfbox/2.0.2/pdfbox-app-2.0.2.jar

cachedir = cache
moduledir = joyodb
joyopdf = $(cachedir)/joyokanjihyo_20101130.pdf
joyotxt = $(cachedir)/joyokanjihyo_20101130.txt
pdfbox = $(cachedir)/pdfbox-app-2.0.2.jar

all: $(joyotxt) joyodb/defs.py $(moduledir)/__init__.py

$(joyotxt): $(joyopdf) $(pdfbox)
	java -jar $(pdfbox) ExtractText $(joyopdf) -console > $(joyotxt)
	@# pdfbox generates ASCII bells (\x07) for some reason.
	sed -e "s/\x07//g" -i $(joyotxt)
$(joyopdf):
	wget $(joyopdf_url) -O $(joyopdf) 
$(pdfbox):
	wget $(pdfbox_url) -O $(pdfbox)

$(moduledir)/__init__.py: $(moduledir)/__init__.py.in
	@echo "Building $@."
	@echo "Autogenerated from $(moduledir)/__init.py.in; do not edit directly." \
	    > $(moduledir)/__init__.py

	sed -e "s,\$$JOYOHYO_TXT,'`readlink -f $(joyotxt)`',"\
	    $(moduledir)/__init__.py.in \
	    >> $(moduledir)/__init__.py

clean:
	rm $(cachedir)/* $(moduledir)/__init__.py

.PHONY: all clean
